module.exports.keys = {
  'power': 'Power', 
  'poweron': 'Power On',
  'poweroff': 'Power Off',
  'format': 'Format',
  'pause': 'Pause', 
  'rew': 'Rewind',
  'replay': 'Replay',
  'stop': 'Stop',
  'advance': 'Advance',
  'ffwd': 'Fast Forward',
  'record': 'Record', 
  'play': 'Play',
  'guide': 'Guide', 
  'active': 'Active',
  'list': 'List',
  'exit': 'Exit',
  'back': 'Back',
  'menu': 'Menu',
  'info': 'Info', 
  'up': 'Up',
  'down': 'Down',
  'left': 'Left',
  'right': 'Right',
  'select': 'Select', 
  'red': 'Red',
  'green': 'Green',
  'yellow': 'Yellow', 
  'blue': 'Blue',
  'chanup': 'Channel Up',
  'chandown': 'Channel Down', 
  'prev': 'Previous', 
  '0': 'Zero', 
  '1': 'One', 
  '2': 'Two', 
  '3': 'Three',
  '4': 'Four',
  '5': 'Five', 
  '6': 'Six',
  '7': 'Seven',
  '8': 'Eight', 
  '9': 'Nine',
  'dash': 'Dash', 
  'enter': 'Enter'
}